//! Byte-identity guard (jilog#heyg lens): a fully populated digest for a
//! configuration WITHOUT the new keys must not change by a single byte.
//! The golden file was generated by this test on the pre-change renderer
//! (`UPDATE_GOLDEN=1 cargo test -p jilog-review --test golden_digest`) and
//! is compared byte-for-byte afterwards. Regenerate ONLY when a change to
//! the digest format is intended and reviewed.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::Path;
use std::str::FromStr;

use jilog_review::{
    render_digest, signal_title, Correction, DeferralSignal, ErrorSignal, IssueRef, PatternSignal,
    PersonaCounts, Signal, SpendSummary, Workaround,
};
use rust_decimal::Decimal;

const GOLDEN: &str = "tests/golden/learning-digest.md";

fn render_fixture() -> String {
    let c1 = Correction {
        session_id: "842c45ce-77b2-4d72-b995-f2a10466eb40".into(),
        context: "do granola re-auth".into(),
        ..Default::default()
    };
    let c2 = Correction {
        session_id: "chat-1".into(),
        seat: Some("codex-02".into()),
        context: "no, use the gog cli".into(),
        persona: Some("jibot".into()),
        channel: Some("The vibez".into()),
        ..Default::default()
    };
    let e1 = ErrorSignal {
        session_id: "0e91a2b4-7d3f-4e2a-9c1b-44a7f3d8a1e2".into(),
        tool_name: "bash".into(),
        message: r#"{"error":null,"output":{"returncode":101,"stderr":"error[E0308]: mismatched types","stdout":""},"success":false}"#.into(),
        ..Default::default()
    };
    let w1 = Workaround {
        session_id: "0000000000000000-79f0e43ee2304cdb_self".into(),
        pattern: "TODO".into(),
        context: "All data collected. Let me update the todo list and finalize".into(),
        ..Default::default()
    };
    let d1 = DeferralSignal {
        session_id: "ae5a0552-47f6-4030-af78-09fe71542d3d".into(),
        item: "next session".into(),
        ..Default::default()
    };
    let p1 = PatternSignal {
        session_id: "ee58d934-1049-4da0-b5b3-9a00f50efcc7".into(),
        seat: Some("seat-03".into()),
        description: "stuck loop".into(),
        pattern_kind: "stuck_loop".into(),
        evidence: "`bash` x6 identical arguments 01:35-01:54".into(),
        ..Default::default()
    };
    let mut p0 = HashMap::new();
    p0.insert(
        "bash".to_string(),
        BTreeSet::from(["s1".to_string(), "s2".to_string(), "s3".to_string()]),
    );
    let d = |s: &str| Decimal::from_str(s).unwrap();
    let spend = SpendSummary {
        total_cost_usd: Some(d("4.2")),
        sessions_with_stats: 3,
        sessions_with_cost: 2,
        input_tokens: 1000,
        output_tokens: 50,
        role_costs: BTreeMap::from([("(root)".to_string(), d("1.2")), ("explore".to_string(), d("3"))]),
        model_costs: BTreeMap::from([("claude-opus-5".to_string(), d("4.2"))]),
    };
    let recurrence =
        HashMap::from([(signal_title(&Signal::Correction(c1.clone())), "$4.20".to_string())]);
    let w1_title = signal_title(&Signal::Workaround(w1.clone()));
    let issues = HashMap::from([(
        w1_title.clone(),
        IssueRef { id: "#7".into(), backend: "kata".into(), url: None, title: w1_title },
    )]);
    let personas = BTreeMap::from([(
        "jibot@The vibez".to_string(),
        PersonaCounts {
            persona: "jibot".into(),
            channel: Some("The vibez".into()),
            sessions: 2,
            corrections: 1,
            errors: 0,
            workarounds: 0,
            deferrals: 0,
            patterns: 0,
            input_tokens: 5000,
            output_tokens: 250,
            cost_usd: Some(d("0.5")),
        },
    )]);
    render_digest(
        "2026-09-16",
        &[c1, c2],
        &[e1],
        &[w1],
        &[d1],
        &[p1],
        &p0,
        Some(&spend),
        &recurrence,
        &issues,
        &personas,
    )
}

#[test]
fn digest_bytes_match_golden() {
    let got = render_fixture();
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    if std::env::var_os("UPDATE_GOLDEN").is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &got).unwrap();
    }
    let want = std::fs::read_to_string(&path)
        .expect("golden missing — generate it ONCE on the pre-change renderer with UPDATE_GOLDEN=1");
    assert_eq!(got, want, "digest bytes changed for a configuration without the new keys");
}
